services:
  numberstovoice:
    sqlserver:
        container_name: sqlserver
        image: mcr.microsoft.com/mssql/server:2022-latest
        environment:
          SA_PASSWORD: "yourStrong#Password"
          ACCEPT_EULA: "Y"
        ports:
          - "1433:1433"
    build:
      context: .
      dockerfile: NumbersToVoice/Dockerfile
